### ISSUE TITLE
TRFC Settings

### ISSUE THREAD

**Issue by amittalkin** [integralfx/DDR4XMPEditor#10]
When system boots with custom XMP settings, it changes TRFC value. I had set it for 490 ticks but it sets 630.

**Comment by integralfx** [comment]
Not all timings are set by the BIOS when loading XMP.

From memory on my setup, it was only the primary timings and I think tRRDS/L and tFAW.

**Comment by amittalkin** [comment]
So TRFC we set in XMP has no impact on actual timing set by system? other settings from XMP loaded just fine, only TRFC, along with TRFC2 and TRFC4 were different than what was set in XMP. Thaiphoon shows XMP has TRFC settings which I have set them to, But somehow it loads different values when system boots. So bios adjust it automatically regardless of which TRFC value we set?

p.s. Looks like this is not your software related issue, You can close this after your input :).

**Comment by integralfx** [comment]
BIOS doesn't load the tRFC you programmed. It will just default to JEDEC timings (350ns).

> p.s. Looks like this is not your software related issue,

Yeah, this is a BIOS issue so nothing I can do about that, but if Thaiphoon is reading the timings you've programmed then my program is working as expected.
