### ISSUE TITLE
Unable to write spd

### ISSUE THREAD

**Issue by specuu** [integralfx/DDR4XMPEditor#11]
Hi, 

I have a problem with writing dumped spd, when I start spd_write and provides informations shown below. Any key closes it.
I don't have a clue how to make the spd_write file to write new spd. Could you help me what should I do?
Thank.

![spd1](https://user-images.githubusercontent.com/92849793/148651979-de6fdba6-76d1-474d-9ff0-f0ad0d691cf8.JPG)

**Comment by specuu** [comment]
Solved

**Comment by integralfx** [comment]
Run it as a command line program and pass the path to the SPD file you want to write.

`spd_write.exe spd_file_to_write.spd`

**Comment by specuu** [comment]
Now it works - I had to move everything to desktop, do bump again, modify and write. It works only this way for me. Thank you.

**Comment by blendcs** [comment]
same issue. cannot write file

**Comment by Kuro-Kuzuri** [comment]
Stuck at trying to write the modified SPD file here as well. Running spd_write.exe in CMD with the path to the SPD file initiates a new dump and even when choosing not to overwrite files it doesn't accept any command to write SPD file to device.

**Comment by blendcs** [comment]
> Stuck at trying to write the modified SPD file here as well. Running spd_write.exe in CMD with the path to the SPD file initiates a new dump and even when choosing not to overwrite files it doesn't accept any command to write SPD file to device.

do u need still solution?
