### ISSUE TITLE
Does it work for intel?

### ISSUE THREAD

**Issue by MikeKostaras** [integralfx/DDR4XMPEditor#18]
Im guessing its just amd only since the bottom only has a guide for ryzen?

**Comment by integralfx** [comment]
My program simply edits SPD files. It doesn't read/write the edited SPD from/to the RAM itself.

It just so happens that on Ryzen you can read/write to the RAM SPD with software.

Not sure if there is something similar for Intel though.

If you can get the SPD file from your RAM, then yes you can use my program to edit it.
