### ISSUE TITLE
Where to find XMP 2.0 spec, pretty please? :)

### ISSUE THREAD

**Issue by void-spark** [integralfx/DDR4XMPEditor#23]
Like title, I want to write a bit of a parser to toy with, but I can't for the life of me find where to get the spec :)
And it seems like by some magic you did have it available :)

**Comment by integralfx** [comment]
https://en.wikipedia.org/wiki/Serial_presence_detect#DDR4_SDRAM

https://gist.github.com/integralfx/bfaa68a39b63ad44184f426bb6bfc9e4

I mostly reverse engineered the spec through Thaiphoon Burner and referencing the DDR3 XMP spec

**Comment by void-spark** [comment]
No spec then, impressive work! Thank you! :)
