### ISSUE TITLE
can't locate spd_write.exe nor spd_read.exe files

### ISSUE THREAD

**Issue by ziv01** [integralfx/DDR4XMPEditor#25]
can't locate spd_write.exe nor spd_read.exe files

**Comment by integralfx** [comment]
See https://github.com/integralfx/DDR4XMPEditor/issues/24

**Comment by ziv01** [comment]
Thanks:)
BTW, I checked with thiaphoon burner and it seems my dimms are locked , RSWP
I can't write to the dimms , any suggestion on how to unlock ?

Thanks

‫בתאריך יום א׳, 17 במרץ 2024 ב-3:06 מאת ‪integralfx‬‏ <‪
***@***.***‬‏>:‬

**Comment by integralfx** [comment]
https://forums.evga.com/My-Arduinobased-RAM-SPD-readerwriter-free-and-open-source-m3053544.aspx

**Comment by ziv01** [comment]
Thanks :)

‫בתאריך יום ב׳, 18 במרץ 2024 ב-7:29 מאת ‪integralfx‬‏ <‪
***@***.***‬‏>:‬
