### ISSUE TITLE
Does setting the 'value' timings on the left do anything ?

### ISSUE THREAD

**Issue by Panjaksli** [integralfx/DDR4XMPEditor#30]
For example is there any difference between 'full' CL 19 with value of 95 and CL 19 with value 91 ?
 I'm tinkering with this, because CL18 doesn't boot, but CL 19 does, even when I lower it just one step above CL 18.
 Didn't see any improvement in latency, nor stability issues though. My thinking is, that commands can only be dispatched on each clock cycle, so how would the timing work otherwise no ?

**Comment by integralfx** [comment]
I'm not sure what you mean by  'full' CL 19 with value of 95 and CL 19 with value 91

Can you post a screenshot?

**Comment by Panjaksli** [comment]
![image](https://github.com/user-attachments/assets/02f0a704-1fe4-4b84-97f7-3240a9d3d686)

I've studied how SPD info is stored in the meanwhile. The left value is apparently in multiples of MTB, which is fixed to 0.125 ns. So my guess is the CPU sets its own timings according to the time * frequency, rounded to nearest (larger) number of cycles ?

**Comment by integralfx** [comment]
Yes, that's correct

`Time (ns) = Value * MTB + Offset`, where MTB is 0.125 ns

`Ticks = Frequency (ns) /  Time (ns)`, rounded up to the nearest whole number

**Comment by Panjaksli** [comment]
Okay, pretty much solved, hope it helps other people looking for the same stuff.
